// ==UserScript==
// @name         🔒 MTurk Earnings → Firebase + Alerts (Secure VM)
// @namespace    ab2soft.secure
// @version      3.3
// @description  Sync MTurk earnings to Firebase only when changed, password locked per worker
// @match        https://worker.mturk.com/earnings*
// @grant        GM_getValue
// @grant        GM_setValue
// ==/UserScript==

(async()=>{const e="9b724d9df97a91d297dc1c714a3987338ebb60a2a53311d2e382411a78b9e07d";
async function t(t){const n=new TextEncoder().encode(t),a=await crypto.subtle.digest("SHA-256",n);return Array.from(new Uint8Array(a)).map(e=>e.toString(16).padStart(2,"0")).join("")}
function n(){try{const e=document.querySelectorAll('[data-react-props*="textToCopy"]');for(const t of e){const e=t.getAttribute("data-react-props");if(e){const t=JSON.parse(e.replace(/&quot;/g,'"'));if(t.textToCopy?.match(/^A[0-9A-Z]+$/))return t.textToCopy}}const t=document.body.innerText.match(/A[0-9A-Z]{10,}/);return t?t[0]:"N/A"}catch{return"N/A"}}
async function a(){try{const e=await fetch("https://api.ipify.org?format=json");return(await e.json()).ip}catch{return"0.0.0.0"}}
function r(){const e=document.body.innerHTML,t=e.match(/Current Earnings: \$([0-9.]+)/)?.[1]||"0",n=e.match(/bank account <a href="\/direct_deposit">([^<]+)<\/a>/)?.[1]?.trim()||"N/A",a=e.match(/on ([A-Za-z]+ \d{2}, \d{4})/)?.[1]||"N/A",r=e.match(/amountRequested&quot;:([0-9.]+),.*?requestedDate&quot;:&quot;([0-9/]+)&quot;/),o=r?r[1]:"0",c=r?r[2]:"N/A";return{current:t,bank:n,nextTransfer:a,lastTransferAmount:o,lastTransferDate:c}}
const{initializeApp:o}=await import("https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js"),{getFirestore:c,doc:s,getDoc:i,setDoc:l,serverTimestamp:d}=await import("https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js"),p={apiKey:"AIzaSyCCtBCAJvQCDj8MXb2w90qYUqRrENIIGIQ",authDomain:"mturk-monitordeep.firebaseapp.com",projectId:"mturk-monitordeep",storageBucket:"mturk-monitordeep.firebasestorage.app",messagingSenderId:"58392297487",appId:"1:58392297487:web:1365ad12110ffd0586637a"},g=o(p),f=c(g),m=n();if(!m||"N/A"===m)return void console.warn("⚠️ No worker ID detected.");const h=`auth_${m}`,u=GM_getValue(h,!1);if(!u){const n=prompt(`🔒 Enter password to enable Firebase sync for Worker ${m}:`);if(!n)return void alert("❌ Access denied.");const a=await t(n);if(a!==e)return void alert("❌ Incorrect password.");GM_setValue(h,!0),alert(`✅ Access granted for Worker ${m}.`)}async function y(){const e=await a(),t=r(),{current:n,bank:o,nextTransfer:c,lastTransferAmount:p,lastTransferDate:g}=t,h=s(f,"earnings_logs",m),u=await i(h);let v="OK",w=!1;const E={workerId:m,currentEarnings:n,lastTransferAmount:p,lastTransferDate:g,nextTransferDate:c,bankAccount:o,ip:e,alert:v,timestamp:d()};if(u.exists()){const t=u.data();if(t.bankAccount&&t.bankAccount!==o)return v="⚠️ BANK CHANGED",await l(h,{alert:v,timestamp:d()},{merge:!0}),void console.warn("🚨 ALERT: Bank changed.");if(t.ip&&t.ip!==e)return v="⚠️ IP CHANGED",await l(h,{alert:v,timestamp:d()},{merge:!0}),void console.warn("🚨 ALERT: IP changed.");for(const e of Object.keys(E))if("timestamp"!==e&&E[e]!==t[e]){w=!0;break}if(!w)return void console.log("⏸ No update needed.")}else w=!0;w&&(await l(h,E,{merge:!0}),console.log("✅ Uploaded:",E))}y();})();
